name: Add a new GitHub Project card linked to a GitHub issue to the specified project column
on: 
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

jobs:
  github-actions-automate-projects:
    runs-on: ubuntu-latest
    steps:
    - name: Add pr to 'Quality Assurance - Code review: Ready for review'
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/MisterChocker/test_repo/projects/1
        GITHUB_PROJECT_COLUMN_NAME: "🟡 Code review: Ready for review"
