name: Move new issues into Triage

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    permissions:
      repository-projects: write
    steps:
      - uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: Backlog
          column: Triage
          repo-token: ${{ secrets.GITHUB_TOKEN }}
